// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8gjloWB9hHgY0VSUvtj3b0wvKewLIkI',
    appId: '1:117757033847:web:58d5fb39de0ca84de2f572',
    messagingSenderId: '117757033847',
    projectId: 'test-project-d2494',
    authDomain: 'test-project-d2494.firebaseapp.com',
    storageBucket: 'test-project-d2494.appspot.com',
    measurementId: 'G-QDWLFLMWDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQjsZzqkdTAPU41J9PjiUabIzen54r_E',
    appId: '1:117757033847:android:b6d5ba6bbc86fac7e2f572',
    messagingSenderId: '117757033847',
    projectId: 'test-project-d2494',
    storageBucket: 'test-project-d2494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8cN-ALSXzVqeJ42qeBnBoCuH4oFnCNRI',
    appId: '1:117757033847:ios:a80fe724bd405b79e2f572',
    messagingSenderId: '117757033847',
    projectId: 'test-project-d2494',
    storageBucket: 'test-project-d2494.appspot.com',
    iosClientId: '117757033847-60mc30gplcp342ek3gcvc47690cvhb3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8cN-ALSXzVqeJ42qeBnBoCuH4oFnCNRI',
    appId: '1:117757033847:ios:a80fe724bd405b79e2f572',
    messagingSenderId: '117757033847',
    projectId: 'test-project-d2494',
    storageBucket: 'test-project-d2494.appspot.com',
    iosClientId: '117757033847-60mc30gplcp342ek3gcvc47690cvhb3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
